spring.application.name=MissionControl


spring.datasource.url=jdbc:postgresql://localhost:5433/mission_control
spring.datasource.username=postgres
spring.datasource.password=0987654321
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console (optional)
spring.jpa.show-sql=true
